/**
 * Git status file representation
 * XY format where X = index status, Y = working tree status
 */
export interface GitStatusFile {
  /** Path relative to repo root */
  path: string;
  /** Status in the index (staged) */
  indexStatus: GitFileStatus;
  /** Status in the working tree */
  workingTreeStatus: GitFileStatus;
  /** Original path if renamed/copied */
  originalPath?: string;
}

/**
 * Possible file statuses from git status --porcelain
 */
export type GitFileStatus =
  | "?" // Untracked
  | "A" // Added
  | "M" // Modified
  | "D" // Deleted
  | "R" // Renamed
  | "C" // Copied
  | "U" // Updated but unmerged
  | "!" // Ignored
  | " " // Unchanged
  | "T"; // Type changed

/**
 * Categorized file collections
 */
export interface CategorizedFiles {
  /** Files staged for commit (indexStatus !== " ") */
  staged: GitStatusFile[];
  /** Modified files not staged (indexStatus === " " && workingTreeStatus !== " ") */
  changes: GitStatusFile[];
  /** Untracked files (indexStatus === "?" || workingTreeStatus === "?") */
  untracked: GitStatusFile[];
  /** Conflict/unmerged files */
  conflicted: GitStatusFile[];
}

/**
 * Hierarchical tree node for file display
 */
export interface FileTreeNode {
  /** Display name (file or folder name) */
  name: string;
  /** Full path from repo root */
  path: string;
  /** Whether this is a directory */
  isDirectory: boolean;
  /** Child nodes if directory */
  children: FileTreeNode[];
  /** File status info (only for files) */
  fileInfo?: GitStatusFile;
}

/**
 * Complete git repository status
 */
export interface GitRepoStatus {
  /** Current branch name */
  branch: string;
  /** Upstream branch if any */
  upstream?: string;
  /** Number of commits ahead of upstream */
  aheadCount: number;
  /** Number of commits behind upstream */
  behindCount: number;
  /** All categorized files */
  files: CategorizedFiles;
  /** Total file count across all categories */
  totalFiles: number;
  /** Whether we're in a git repository */
  isRepo: boolean;
}

/**
 * A comparison target used by compare mode.
 */
export type CompareMode = "base-branch" | "base-commit" | "single-commit";

export type CompareTarget = {
  /** Which compare tab produced this target. */
  mode: CompareMode;
  /** Git ref used as the selection value. */
  ref: string;
  /** Human-readable label shown in the UI. */
  label: string;
};

/**
 * Branch compare state
 */
export interface CompareState {
  /** The active compare mode. */
  mode: CompareMode;
  /** Base ref used to generate the diff. */
  baseRef: string;
  /** The user-facing compare target ref. */
  compareRef: string;
  /** Target ref for single-commit compare, otherwise null. */
  targetRef: string | null;
  /** Human-readable label for the base */
  baseLabel: string;
  /** Files changed between baseBranch and HEAD */
  files: GitStatusFile[];
}

/**
 * Resolved refs used to load a compare-mode diff or file list.
 */
export interface CompareResolution {
  /** Git ref used for the left side of the diff. */
  baseRef: string;
  /** The original target requested by the user. */
  compareRef: string;
  /** Git ref used for the right side of the diff. */
  targetRef: string | null;
  /** Git revision range used for file listing and diff generation. */
  revisionRange: string;
  /** Human-readable label for the left side. */
  baseLabel: string;
}

/**
 * Cached diff payload returned directly from git.
 */
export interface FileDiffSource {
  /** Unified patch text generated by git. */
  patch: string;
  /** Original path when the file was renamed or copied. */
  originalPath?: string;
}

/**
 * Repo monitor event type.
 */
export type RepoChangeKind = "content" | "metadata";

export type RepoMonitorMode = "native" | "polling";

/**
 * Listener notified when the repo changes.
 */
export type RepoChangeListener = (kind: RepoChangeKind) => void;

/**
 * Disposable repo monitor handle.
 */
export interface RepoMonitor {
  mode: RepoMonitorMode;
  dispose: () => Promise<void>;
}

export type { RepoContext } from "./repo";
